apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transformer
spec:
  template:
    spec:
      containers:
      - image: gcr.io/vaikas-knative/cmd-736bbd9d5a42b6282732cf4569e3c0ff@sha256:f069e4e58d6b420d66304d3bbde019160eb12ca17bb98fc3b88e0de5ad2cacd1

---
